#!/bin/bash
karim is a farmer
He like to play football at sunday
He like to buy horses
He gives lot of attention to his familly
He mades a lot of money these last years
But, he lost them in gambling
So, he solds his farm and got divorse with his wife
Now Karim is lowly
Karim got the number of Karima, the mamanger of the casino
He got the winning number and gain a lot of money
Karim get in love with karima so they got married
Karim get rich, his ex saws here with karima and his new child
His ex suicid 
Fuch the casino


123456789 these are the basic number of the dashboard
